
services:
  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_budgetwise
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - budgetwise_network

volumes:
  postgres_data:

networks:
  budgetwise_network:
    driver: bridge
